# This workflow will install Python dependencies and post the tweet every day at 3am.

name: Oh Boy 3am

on:
#   # as much as I wish this would work, Github Actions scheduling is too inconsistent.
#   # see here: https://upptime.js.org/blog/2021/01/22/github-actions-schedule-not-working/
#   schedule:
#     - cron: "00 07 * * *" # run daily at 7:00 UTC (3am EDT)
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  post-tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Post tweet
        # run: python main.py
        run: python -c "print('Hello, world!')"
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY}}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET}}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN}}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET}}
