name: Post Tweet

on:
  workflow_call:
  workflow_dispatch:

env:
  DENO_DIR: ~/.deno

jobs:
  post-tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.30.x

      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.DENO_DIR }}
          key: deno-${{ hashFiles('deno.lock')}}

      - name: Install deno dependencies
        run: deno task install

      - name: Post tweet
        run: deno task run
        env:
          MASTODON_SERVER_URL: https://mas.to
          MASTODON_API_TOKEN: ${{ secrets.MASTODON_API_TOKEN }}
